### ISSUE TITLE
Issue with library reporting same object has different keys.

### ISSUE THREAD

**Issue by JoshGlazebrook** [codsen/object-no-new-keys#1] opened 2017-07-23 01:09 UTC
So I have this test code to reproduce this issue I'm having. In the test code, obj1 and obj2 are identical, yet I am receiving the following result from this library:

```
[ 'categories[2].suggestions[0].link',
  'categories[2].suggestions[1].link',
  'categories[3].suggestions[0].link',
  'categories[3].suggestions[1].link' ]
```

Test code:

https://gist.github.com/JoshGlazebrook/46a65378023f6e6ecdeb0caf8ecb280f

**Comment by revelt** [comment] 2017-07-23 11:43
Thank you 👍  I'll investigate

**Comment by revelt** [comment] 2017-07-23 12:04
Hi Josh!

I found the reason. In short, it's an expected behaviour.

There are two [modes](https://github.com/codsen/object-no-new-keys#two-modes), passed via options object, {mode: 1 OR 2}.

Second mode is the default - it will expect that all your arrays will be normalised, so there's no point comparing every `i`'th element of the input with the `i`'th element of the reference, so it compares every element of the input with the FIRST element of the reference. (This feature is handy when your reference has only one element within each array, but your input you're comparing has many. Otherwise, you'd get all those elements second-onwards reported as rogue keys, not present in reference).

So, here's what's happening. Even though you feed in the same object, it will compare the _to-be-checked-input_'s keys in arrays TO THE FIRST element of each array in the _reference-input_. That's default behaviour of mode No.2. The first element in your example happened to have `link` key missing, so reference didn't receive it and flagged all `link` keys as rogue.

If you switch to mode No.1, the library would not take any assumptions when comparing and would compare each array, each element of reference with each array, each element of to-be-checked-input. Instead of every element of array to first element in reference.

Here's [proof](https://runkit.com/embed/emfqjp55pn1z) all is OK in mode No.1. - when calling this lib via `console.log(tester(obj1, obj2, {mode: 1}));` it returns an empty array.

I'll close this issue because it's an expected behaviour of default mode No.2.

**Closed by revelt** 2017-07-23 12:04 UTC

**Comment by JoshGlazebrook** [comment] 2017-07-23 21:06
Ah I see what I was doing wrong.

I originally tried option 1, but was passing just an integer and not the { mode: 1 } object.

**Comment by revelt** [comment] 2017-07-23 21:15
I see! We could actually accept integer, but I'm preparing for the future, maybe there will be more options..
